title: DaPlayer - Listen to your SoundCloud, YouTube and local musics

baseurl: ""
url: "http://daplayer.github.io"
exclude: ["css/_*.less", README.md, Rakefile, Gemfile, Gemfile.lock]

version: 1.0.0.beta
navs:
  download:
    title:
      en: Download
      fr: Téléchargement
    href:
      en: /download/
      fr: /fr/telechargement/
    icon: desktop-download
  documentation:
    title:
      en: Documentation
      fr: Documentation
    href:
      en: /documentation/
      fr: /fr/documentation/
    icon: book
  souce-code:
    title:
      en: Source Code
      fr: Code Source
    href:
      en: "https://github.com/daplayer/daplayer"
      fr: "https://github.com/daplayer/daplayer"
    icon: mark-github

# Home translations
home:
  sc_title:
    en: Listen to your SoundCloud musics ...
    fr: Écoutez vos musiques SoundCloud ...
  sc_desc:
    en: Your stream, favorites and playlists are automatically synced so you can listen to your whole SoundCloud collection ...
    fr: Votre fil d'actualités, vos favoris et playlists sont synchronisés automatiquement ; vous pouvez donc écouter toute votre bibliothèque !
  yt_title:
    en: ... Watch YouTube videos ...
    fr: ... Regardez des vidéos YouTube ...
  yt_desc:
    en: Your YouTube collection is available as well so you can just listen to your favorite musics or switch to the video mode and enjoy the clip !
    fr: Votre collection YouTube est également disponible, vous pouvez donc écouter vos musiques ou passer en mode vidéo pour apprécier le clip !
  local_title:
    en: ... Or enjoy your local library !
    fr: ... Ou apprécier la musique de votre ordinateur !
  local_desc:
    en: Your local library will be properly organized as well with your singles and albums ! MP3, Wav, Ogg and M4A/AAC are supported at the moment.
    fr: Votre bibliothèques locale sera également correctement organisé avec vos singles et albums ! Les formats MP3, Wav, Ogg et M4A/ACC sont supportés.

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    default_lang: javascript
